name: Daily Business Dossier Agent

on:
  schedule:
    # اجرا در ساعت 16:30 UTC (۸ شب به وقت ایران) - هر دو روز یک بار
    - cron: '30 16 */2 * *'
  workflow_dispatch: # اجازه اجرای دستی

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run the agent
        env:
          AVALAI_API_KEY: ${{ secrets.AVALAI_API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python agent.py
